import {Inter} from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/components/materialTailwind";
import theme from "@/const/theme";
import Navbar from "@/components/Navbar";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <ThemeProvider value={theme}>
            <div className={`bg-white`}>
                <Navbar/>
                {children}
            </div>
        </ThemeProvider>
        </body>
        </html>
    );
}
